//! Derives the primitive-class checklist and each class's own method-name
//! table from `Setup.cpp` at build time -- the model is `rexx-inventory`'s
//! `build.rs`: the C++ tree is the source of truth, nothing here is
//! hand-maintained, and nothing generated is written into `src/`.
//!
//! Two tables come out of one file:
//!
//! * `SETUP_CLASSES` -- the checklist. Every `X::createInstance();` call in
//!   `MemoryObject::createImage`, in file order -- a Rust line scan
//!   (`parse_checklist`, below), not a shelled-out `grep`, but it matches
//!   the same lines the brief's own specified command
//!   (`/bin/grep -aE "createInstance\(\)"`) does. This is the C++ *type*
//!   name (`RexxInteger`, `ArrayClass`, ...), not necessarily the
//!   Rexx-visible id string.
//! * `CLASS_DEFINITIONS` -- for every `StartClassDefinition(Name)` block up
//!   to its matching `EndClassDefinition`/`EndSpecialClassDefinition(Name)`,
//!   the ordered sequence of `AddMethod`/`AddClassMethod`/
//!   `InheritInstanceMethods`/`RemoveMethod`/`HideMethod` operations it
//!   contains, keyed by `Name` -- the macro-block name, which for four of
//!   the thirty-one checklist entries differs from the C++ type name
//!   (`RexxClass` -> `Class`, `RexxInteger` -> `Integer`, `RexxString` ->
//!   `String`, `RexxObject` -> `Object`; every other entry's block name is
//!   its C++ type name with a trailing `Class` stripped, or identical when
//!   there is none). `rexx-classes/src/native_classes.rs` carries that
//!   correspondence explicitly and asserts it against both derived lists.

use std::path::{Path, PathBuf};

const SETUP_CPP: &str = "../../../interpreter/memory/Setup.cpp";

fn main() {
    println!("cargo::rerun-if-changed={SETUP_CPP}");
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets OUT_DIR"));
    let src = std::fs::read_to_string(Path::new(SETUP_CPP))
        .unwrap_or_else(|e| panic!("cannot read {SETUP_CPP}: {e}"));

    std::fs::write(out.join("setup_classes.rs"), generate(&src)).expect("writing setup_classes.rs");
}

fn generate(src: &str) -> String {
    let checklist = parse_checklist(src);
    if checklist.len() < 20 {
        panic!(
            "only {} createInstance() calls parsed from Setup.cpp -- the format changed",
            checklist.len()
        );
    }
    let definitions = parse_definitions(src);
    if definitions.len() < 20 {
        panic!(
            "only {} StartClassDefinition blocks parsed from Setup.cpp -- the format changed",
            definitions.len()
        );
    }

    let mut out = String::from(
        "// Generated by build.rs from interpreter/memory/Setup.cpp. Do not edit.\n\n\
         /// One `Setup.cpp` bootstrap macro invocation, in file order.\n\
         #[derive(Clone, Copy)]\n\
         pub enum Op {\n\
         \x20   AddClassMethod(&'static str),\n\
         \x20   AddInstanceMethod(&'static str),\n\
         \x20   InheritInstanceMethods(&'static str),\n\
         \x20   RemoveInstanceMethod(&'static str),\n\
         \x20   HideInstanceMethod(&'static str),\n\
         }\n\n\
         pub struct ClassDefinition {\n\
         \x20   pub name: &'static str,\n\
         \x20   pub ops: &'static [Op],\n\
         }\n\n\
         /// Every `X::createInstance();` call in `MemoryObject::createImage`,\n\
         /// in file order -- the C++ type name, not the Rexx id string.\n\
         pub static SETUP_CLASSES: &[&str] = &[\n",
    );
    for name in &checklist {
        out.push_str(&format!("    {name:?},\n"));
    }
    out.push_str("];\n\npub static CLASS_DEFINITIONS: &[ClassDefinition] = &[\n");
    for def in &definitions {
        out.push_str("    ClassDefinition { name: ");
        out.push_str(&format!("{:?}", def.name));
        out.push_str(", ops: &[\n");
        for op in &def.ops {
            let rendered = match op {
                Op::AddClassMethod(n) => format!("Op::AddClassMethod({n:?})"),
                Op::AddInstanceMethod(n) => format!("Op::AddInstanceMethod({n:?})"),
                Op::InheritInstanceMethods(n) => format!("Op::InheritInstanceMethods({n:?})"),
                Op::RemoveInstanceMethod(n) => format!("Op::RemoveInstanceMethod({n:?})"),
                Op::HideInstanceMethod(n) => format!("Op::HideInstanceMethod({n:?})"),
            };
            out.push_str("        ");
            out.push_str(&rendered);
            out.push_str(",\n");
        }
        out.push_str("    ]},\n");
    }
    out.push_str("];\n");
    out
}

fn parse_checklist(src: &str) -> Vec<String> {
    let mut names = Vec::new();
    for line in src.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_suffix("::createInstance();") {
            names.push(rest.to_string());
        }
    }
    names
}

enum Op {
    AddClassMethod(String),
    AddInstanceMethod(String),
    InheritInstanceMethods(String),
    RemoveInstanceMethod(String),
    HideInstanceMethod(String),
}

struct ClassDef {
    name: String,
    ops: Vec<Op>,
}

/// Extract the class-method/instance-method distinction and the operation
/// kind from one `Setup.cpp` line, following the macro table at
/// `Setup.cpp:349-398`. Lines this does not recognize (comments, braces,
/// `CompleteClassMethodDefinitions()`, ...) are simply not operations.
fn parse_definitions(src: &str) -> Vec<ClassDef> {
    let mut result = Vec::new();
    let mut current: Option<ClassDef> = None;

    for raw_line in src.lines() {
        let line = raw_line.trim();
        if let Some(name) = macro_arg(line, "StartClassDefinition") {
            assert!(
                current.is_none(),
                "nested StartClassDefinition({name}) before a matching End"
            );
            current = Some(ClassDef {
                name,
                ops: Vec::new(),
            });
            continue;
        }
        if let Some(name) = macro_arg(line, "EndClassDefinition")
            .or_else(|| macro_arg(line, "EndSpecialClassDefinition"))
        {
            let def = current
                .take()
                .unwrap_or_else(|| panic!("End...Definition({name}) with no matching Start"));
            assert_eq!(
                def.name, name,
                "StartClassDefinition({}) closed by a block named {name}",
                def.name
            );
            result.push(def);
            continue;
        }
        let Some(def) = current.as_mut() else {
            continue;
        };
        if let Some(n) = macro_string_arg(line, "AddClassMethod")
            .or_else(|| macro_string_arg(line, "AddClassProtectedMethod"))
            .or_else(|| macro_string_arg(line, "AddClassPrivateMethod"))
            .or_else(|| macro_string_arg(line, "AddClassUnguardedMethod"))
        {
            def.ops.push(Op::AddClassMethod(n));
        } else if let Some(n) = macro_string_arg(line, "AddProtectedMethod")
            .or_else(|| macro_string_arg(line, "AddPrivateMethod"))
            .or_else(|| macro_string_arg(line, "AddUnguardedMethod"))
            .or_else(|| macro_string_arg(line, "AddMethod"))
        {
            def.ops.push(Op::AddInstanceMethod(n));
        } else if let Some(n) = macro_arg(line, "InheritInstanceMethods") {
            def.ops.push(Op::InheritInstanceMethods(n));
        } else if let Some(n) = macro_string_arg(line, "RemoveMethod") {
            def.ops.push(Op::RemoveInstanceMethod(n));
        } else if let Some(n) = macro_string_arg(line, "HideMethod") {
            def.ops.push(Op::HideInstanceMethod(n));
        }
    }
    assert!(current.is_none(), "unterminated StartClassDefinition block");
    result
}

/// `Macro(bareword)` -> `"bareword"`, for macros whose argument is an
/// identifier rather than a quoted string (`StartClassDefinition`,
/// `EndClassDefinition`, `InheritInstanceMethods`).
fn macro_arg(line: &str, macro_name: &str) -> Option<String> {
    let rest = line.strip_prefix(macro_name)?;
    let rest = rest.strip_prefix('(')?;
    let end = rest.find(')')?;
    Some(rest[..end].trim().to_string())
}

/// `Macro("quoted", ...)` -> the unescaped content of the first quoted
/// argument -- every `Add*Method`/`RemoveMethod`/`HideMethod` invocation's
/// method name. The only C escape `Setup.cpp` uses in these strings is a
/// doubled backslash standing for one literal backslash (`"\\="` is the
/// two-character method name `\=`); this unescapes exactly that and
/// nothing else, since nothing else occurs here.
fn macro_string_arg(line: &str, macro_name: &str) -> Option<String> {
    let rest = line.strip_prefix(macro_name)?;
    let rest = rest.strip_prefix('(')?;
    let rest = rest.trim_start();
    let rest = rest.strip_prefix('"')?;
    let mut result = String::new();
    let mut chars = rest.chars();
    loop {
        match chars.next()? {
            '"' => return Some(result),
            '\\' => result.push(chars.next()?),
            c => result.push(c),
        }
    }
}
