//! Embeds the Rexx-written part of the interpreter's own library from the C++
//! tree at build time.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// One embedded program: the name a `CALL` inside the bootstrap resolves it
/// by, the path it is read from relative to this crate, and its pinned
/// sha256.
struct Source {
    name: &'static str,
    path: &'static str,
    sha256: &'static str,
}

const SOURCES: &[Source] = &[
    Source {
        name: "CoreClasses.orx",
        path: "../../../interpreter/RexxClasses/CoreClasses.orx",
        sha256: "c00727ab66e0fd862f12a7c023656c948259837b8432fa0d149bd6938fe2ff47",
    },
    Source {
        name: "StreamClasses.orx",
        path: "../../../interpreter/RexxClasses/StreamClasses.orx",
        sha256: "b61440a82bd3b2c198a84f44f8f9f0057aed847750c7b9e2c7fc05a819b92bba",
    },
    Source {
        name: "PlatformObjects.orx",
        path: "../../../interpreter/platform/unix/PlatformObjects.orx",
        sha256: "04f89bb9b1ff2f5ee06f774f6b1b4159699198cc7da48c8703a9a0ab7fe8435e",
    },
];

fn main() {
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets OUT_DIR"));
    let mut generated = String::from(
        "// Generated by build.rs from the interpreter's own .orx sources.\n\
         // Do not edit.\n\
         pub static PROGRAMS: &[Program] = &[\n",
    );
    for source in SOURCES {
        println!("cargo::rerun-if-changed={}", source.path);
        let path = Path::new(source.path);
        let bytes =
            std::fs::read(path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
        let actual = sha256_hex(&bytes);
        if actual != source.sha256 {
            panic!(
                "{} has sha256 {actual}, and this crate pins {}. The interpreter's own \
                 .orx sources are read-only here; if one really did change upstream, the \
                 pin moves in the same commit that re-verifies the bootstrap against it.",
                path.display(),
                source.sha256
            );
        }
        writeln!(
            generated,
            "    Program {{ name: {:?}, source: include_bytes!({:?}), sha256: {:?} }},",
            source.name,
            std::fs::canonicalize(path)
                .unwrap_or_else(|e| panic!("cannot canonicalize {}: {e}", path.display())),
            source.sha256,
        )
        .expect("writing to a String cannot fail");
    }
    generated.push_str("];\n");
    std::fs::write(out.join("programs.rs"), generated).expect("writing programs.rs");
}

/// SHA-256 of `bytes`, lower-case hex.
fn sha256_hex(bytes: &[u8]) -> String {
    const K: [u32; 64] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4,
        0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe,
        0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f,
        0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
        0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc,
        0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
        0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116,
        0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7,
        0xc67178f2,
    ];
    let mut h: [u32; 8] = [
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab,
        0x5be0cd19,
    ];

    let mut message = bytes.to_vec();
    let bit_length = (bytes.len() as u64) * 8;
    message.push(0x80);
    while message.len() % 64 != 56 {
        message.push(0);
    }
    message.extend_from_slice(&bit_length.to_be_bytes());

    for block in message.as_chunks::<64>().0 {
        let mut w = [0u32; 64];
        for (slot, word) in w.iter_mut().zip(block.as_chunks::<4>().0) {
            *slot = u32::from_be_bytes(*word);
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16]
                .wrapping_add(s0)
                .wrapping_add(w[i - 7])
                .wrapping_add(s1);
        }
        let [mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut hh] = h;
        for i in 0..64 {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let ch = (e & f) ^ ((!e) & g);
            let temp1 = hh
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(K[i])
                .wrapping_add(w[i]);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let temp2 = s0.wrapping_add(maj);
            hh = g;
            g = f;
            f = e;
            e = d.wrapping_add(temp1);
            d = c;
            c = b;
            b = a;
            a = temp1.wrapping_add(temp2);
        }
        for (slot, value) in h.iter_mut().zip([a, b, c, d, e, f, g, hh]) {
            *slot = slot.wrapping_add(value);
        }
    }

    let mut hex = String::with_capacity(64);
    for word in h {
        write!(hex, "{word:08x}").expect("writing to a String cannot fail");
    }
    hex
}
