/*----------------------------------------------------------------------------*/
/*                                                                            */
/* Copyright (c) 2026 Rexx Language Association. All rights reserved.          */
/*                                                                            */
/* This program and the accompanying materials are made available under       */
/* the terms of the Common Public License v1.0 which accompanies this         */
/* distribution. A copy is also available at the following address:           */
/* https://www.oorexx.org/license.html                                        */
/*                                                                            */
/*----------------------------------------------------------------------------*/

//! Tables mechanically derived from the C++ tree, plus the one hand-written
//! list that indexes into them.
//!
//! Everything reached through `include!` -- [`errors`]'s whole contents and
//! [`builtins::NAMES`] -- is generated by `build.rs`. Never hand-edit those;
//! the C++ tree is the source of truth and the build script re-derives them.
//! [`builtins::EXCLUDED`] and [`builtins::PARTIALLY_EXCLUDED`] are the
//! exception and each says so at its own definition: a scoping decision is
//! not written down in any C++ file, so there is nothing to derive it from.

pub mod errors {
    include!(concat!(env!("OUT_DIR"), "/errors.rs"));
}

pub mod builtins {
    include!(concat!(env!("OUT_DIR"), "/builtins.rs"));

    /// The builtins `docs/superpowers/plans/phase-4-exclusions.txt` excludes
    /// from Phase 4, whole or in part: its fifteen whole exclusions followed
    /// by its three partial rows.
    ///
    /// **Hand-written, unlike [`NAMES`] beside it.** Which builtins a phase
    /// owes is a decision recorded in that plan file; the C++ tree records
    /// only that the function exists, so no build script can derive this.
    /// Changing a name here without changing the file (or the other way
    /// round) is exactly the drift `rexx-exec/tests/coverage.rs` exists to
    /// catch, and it checks every name here is a real builtin.
    ///
    /// **This is not the excluded-outright set.** Three of these rows are
    /// partial: the name is in scope in one form and excluded in another, so
    /// it must still be exercised. Use [`wholly_excluded`] for the set that
    /// runs nothing; taking the length of this list instead gives eighteen
    /// where the answer is fifteen.
    pub const EXCLUDED: &[&str] = &[
        // Phase 7, streams and platform.
        "CHARIN",
        "CHAROUT",
        "CHARS",
        "LINEIN",
        "LINEOUT",
        "LINES",
        "STREAM",
        "QUALIFY",
        "USERID",
        "SETLOCAL",
        "ENDLOCAL",
        // Phase 10, RXAPI.
        "RXQUEUE",
        "RXFUNCADD",
        "RXFUNCDROP",
        "RXFUNCQUERY",
        // Partial: in scope in one form, excluded in another.
        "VALUE",
        "ADDRESS",
        "QUEUED",
    ];

    /// The subset of [`EXCLUDED`] that is excluded only in part, and so is
    /// still in scope in its other form. Named rather than written as a
    /// literal `3` at the two places that subtract it, because "in
    /// `EXCLUDED`" and "excluded outright" are different sets and the
    /// difference is exactly these names.
    pub const PARTIALLY_EXCLUDED: &[&str] = &["VALUE", "ADDRESS", "QUEUED"];

    /// The builtins excluded outright: [`EXCLUDED`] less
    /// [`PARTIALLY_EXCLUDED`], in `EXCLUDED` order.
    ///
    /// A caller wanting "the names Phase 4 runs nothing for" wants this and
    /// not `EXCLUDED`; the two differ by three, and every count derived from
    /// the wrong one is off by three in a way that still looks plausible.
    pub fn wholly_excluded() -> Vec<&'static str> {
        EXCLUDED
            .iter()
            .copied()
            .filter(|name| !PARTIALLY_EXCLUDED.contains(name))
            .collect()
    }

    /// The builtins Phase 4 must be able to run: every name in [`NAMES`] that
    /// is not excluded outright, in `NAMES` order. A partially excluded name
    /// is in here, because its in-scope form still has to work.
    pub fn in_scope() -> Vec<&'static str> {
        let whole = wholly_excluded();
        NAMES
            .iter()
            .copied()
            .filter(|name| !whole.contains(name))
            .collect()
    }
}
